const tableNames = [
  'listing',
  'user',
  'message',
  'friendship',
  'group',
  'groupParticipation',
  'gameRank',
  'listing',
  'listingComment',
  'profilePageComment',
  'privateMessage',
  'game',
];

/*
    Initial migration that sets up the schema. Do not edit this file. 
    Instead, if you want to update the tables, create a new migration using `npm migrate:make`. 
    Refer to  add_private_message_content_column migration for reference.
*/
exports.up = function (knex) {
  return knex.schema
    .createTable('user', (table) => {
      table.increments();
      table.string('nickname').notNullable().unique();
      table.string('email').notNullable().unique();
      table.string('password').notNullable();
      table.string('profilePicSrc');
      table.boolean('isActive');
      table.boolean('hasNewsletter');
      table.integer('age');
      table.timestamps(true, true);
    })
    .createTable('game', (table) => {
      table.increments();
      table.string('title');
      table.date('releaseDate');
      table.timestamps(true, true);
    })
    .createTable('friendship', (table) => {
      table.increments();
      table.integer('user').notNullable().references('id').inTable('user');
      table.integer('friend').notNullable().references('id').inTable('user');
      table.timestamps(true, true);
    })
    .createTable('group', (table) => {
      table.increments();
      table.string('name').notNullable();
      table.string('description');
      table.string('groupPicSrc');
      table.timestamps();
    })
    .createTable('groupParticipation', (table) => {
      table.increments();
      table.integer('member').notNullable().references('id').inTable('user');
      table.integer('group').notNullable().references('id').inTable('group');
      table.timestamps();
    })
    .createTable('gameRank', (table) => {
      table.increments();
      table.string('title').notNullable();
      table.string('badgeSrc');
      table.float('userScoreAvgMax');
      table.float('userScoreAvgMin');
      table.timestamps(true, true);
    })
    .createTable('listing', (table) => {
      table.increments();
      table.boolean('status');
      table.string('message');
      table.integer('maxNumberOfPlayers');
      table.integer('creator').notNullable().references('id').inTable('user');
      table.integer('listingGame').references('id').inTable('game');
      table.timestamps(true, true);
    })
    .createTable('listingComment', (table) => {
      table.increments();
      table.string('content');
      table
        .integer('commentListing')
        .notNullable()
        .references('id')
        .inTable('user');
      table
        .integer('commentSender')
        .notNullable()
        .references('id')
        .inTable('group');
      table.timestamps(true, true);
    })
    .createTable('profilePageComment', (table) => {
      table.increments();
      table.string('content');
      table
        .integer('commentSender')
        .notNullable()
        .references('id')
        .inTable('user');
      table
        .integer('commentReceiver')
        .notNullable()
        .references('id')
        .inTable('user');
      table.timestamps(true, true);
    })
    .createTable('privateMessage', (table) => {
      table.increments();
      table
        .integer('messageSender')
        .notNullable()
        .references('id')
        .inTable('user');
      table
        .integer('messageReceiver')
        .notNullable()
        .references('id')
        .inTable('user');
      table
        .integer('parentMessageId')
        .notNullable()
        .references('id')
        .inTable('privateMessage');
      table.timestamps(true, true);
    });
};

/* 
The down function should to the opposite of what the up function does.
But since we declare all our tables in a one migration file, it just drops all tables 
*/
exports.down = function (knex) {
  return tableNames.forEach((name) => {
    knex.schema.dropTableIfExists(name);
  });
};
